config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources  :users
  resources  :communities do
    resources :follows, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
  root to: 'communities#index'

  resources :mypage do
    member do
      get 'profile'
    end
  end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :community, optional: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader

   has_many :follows, dependent: :destroy
   
   has_many :users, through: :follows #追加

   has_many :comments, dependent: :destroy

  with_options if: :published? do
    validates :title, presence: true
    validates :introduction, presence: true
   # 複数valitatesをまとめたい場合はwith_optionsを使用（published?はメソッド名またはmodelのboolean項目)
 end

 def published?
  false
 end





end

app/models/follow.rb
class Follow < ApplicationRecord
  validates_uniqueness_of :community_id, scope: :user_id
  belongs_to :user
  belongs_to :community
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :profile_image, ProfileImageUploader

  has_many :communities, dependent: :destroy

  has_many :follows, dependent: :destroy

  has_many :follow_communities, through: :follows #追加

  has_many :comments, dependent: :destroy

  def following?(community)
    self.follows.exists?(community_id: community.id)
  end

  def follow_id(community)
    self.follows.find_by(community_id: community.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create 
    @comment = current_user.comments.new(comment_params) 
    @comment.community_id = params[:community_id]
    if @comment.save!  #@commentにcomments.community_idを渡す、ここが空だとエラーが出ている。
     
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    comment = Comment.find(params[:id]) #dbからCommentモデル
    comment.destroy
    redirect_to communities_path, notice: "投稿を削除しました。"
  end

  
    private
    def comment_params
      params.require(:comment).permit(:content)
    end

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:edit,:show,:update]

  def index
    @communities = Community.all
  end

  def show
    @comments = @community.comments   #投稿詳細に関連付けてあるコメントを全取得
   
    @comment = Comment.new   #投稿詳細画面でコメントの投稿を行うので、formのパラメータ用にCommentオブジェクトを取得
  end

  def edit

    @community = Community.find(params[:id])

  end

  def new
    @community = Community.new
  end

  def create
    @community = current_user.communities.build(community_params)
    if @community.save
      redirect_to community_path(@community), notice: "投稿に成功しました。"
    else
      render :new
    end
  end


  def update
    if @community.update(community_params)
       redirect_to community_path, notice: "投稿を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    community = Community.find(params[:id])
    community.destroy
    redirect_to communities_path, notice: "投稿を削除しました。"
  end


  private
  def community_params
    params.require(:community).permit(:title, :body, :image, :content)
  end

  def set_community
    @community = Community.find(params[:id])
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_variables
  def create
    @follow = current_user.follows.create(community_id:params[:community_id])#フォローしたいコミュニティにフォローを追加する
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @community = Community.find(params[:community_id])#フォローを削除したいコミュニティを探す
    @follow = current_user.follows.find_by(community_id: @community.id)#コミュニティに結びついているフォローを探す
    @follow.destroy#フォローを削除
     redirect_back(fallback_location: root_path)

  end

  private
  def set_variables
    @community = Community.find(params[:community_id])
    @id_name = "#follow-follow-#{@community.id}"
  end

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController

    def profile
      @user = User.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to profile_mypage_path(@user)
  end
end

private
def user_params
  params.require(:user).permit(:username, :profile, :profile_image)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/communities/_form.html.erb
<div class = "container">
      <div class = "col ">
        <div class="card mb-4 " style="width: 40rem;">
        <%= form_for @community do |f| %>
            <div>
                <%= f.label "タイトル:" %>
                <%= f.text_field :title, class: "field a", :style => "width: 35rem;"  %>
            </div>

            <div>
                <%= f.label "内容: " %>
                <%= f.text_area :body, :wrap => "hard", class: "field b", :style => "width: 35rem;"%>
            </div>

            <div>
                <%= f.label "イメージ画像" %>
                <%= f.file_field :image, class: "field -c" %>
            </div>

            <div>
                <%= f.submit '投稿', class:"btn btn-primary btn-lg s-post "%>
            </div>
        <%end%>
        </div>
      </div>
</div> 

<style>
 .card {
   padding: 40px;
   height:500px; 
   margin-left: 250px;
 }

 .field {
   margin-bottom: 40px;
  
 }

 .b {
   height:150px;
   

 }

 .s-post {
   border-radius: 30px;
   margin-left: 200px;
   width: 150px;
  

 }

 



 

</style>

app/views/communities/edit.html.erb
<h2 style="text-align:center;">コミュニティを編集</h2>

<%= render "form" %>

app/views/communities/index.html.erb
<div class="container">
    <div class="row ">
        <% @communities.each do |community| %>    
          <div class="col aaa">
            <%= link_to community_path(community) do %>
                <div class="card shadow-sm" style="height:300px; width:15rem;">
                 <div>
                    <%= image_tag community.image.url, class:"card-img", style:"height: 10rem;" %>
                  </div>
                 
                  <div class="card-body">
                    <%= community.title %>
                  </div>
                  
                </div>
            <%end%>
          </div>
        <%end%>
    </div>
</div> 

<style>
.aaa {
  margin-bottom:3rem;
  position:relative;
}
 
</style>

app/views/communities/new.html.erb
<h5>コミュニティを作成</h5>

<%= render "form" %>

<style>
 h5 {
   text-align:center;
   margin-top:40px;
 }
</style>

app/views/communities/show.html.erb
<div class="container">
  <div class="row c-padding">

    <div class="col">
      <div class="content-image">
        <%= image_tag @community.image.url, :style => "width: 300px; height: 300;",class:"image" %>
      </div>
    </div>
   
      <div class="card mb-4 shadow-sm" style="width: 40rem;">
        <div class="t-content">
          <div class="content-title">
            <%= @community.title %>
          </div>
          <div class="b-tto">
              <div class="button">
                <%= link_to "編集", edit_community_path(@community), class: "edit_button" %>
              </div>
          
              <div class="button">
                <%= link_to "削除", community_path(@community), method: :delete, class: "destroy_button" %>
              </div>
            </div>
          </div>
          <div class="content-body">
            <%= safe_join(@community.body.split("\n"),tag(:br))%>    
          </div>
     </div>
    </div>
  </div>


  <h2>コメント一覧</h2>
  <% @comments.each do |c| %>
    <div>
      <%= c.content %> 
      <%= link_to "削除", community_comment_path(@community,c), method: :delete %>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@community, @comment], local: true ) do |f| %>
      <%= f.text_field :content %>

      <br>
      <%= f.submit 'コメントする' %>

    <%end%>
  <%end%>
  
</div>
    
　

 <style>
  .button {
    text-align: right;

  }

  .card {
    height: 300px;
    border-radius: 10px;
  }


  .content-title {
   
  /* display:inline-block; */
  font-size: 25px;
  }

 .image {
   border-radius: 10px;
 }

 .col {
   /* display:inline-block; */
 }

 .t-content {
   border-bottom:solid 1px;
  
 }

 .b-tto {
   /* display:inline-block; */
   /* padding-left:500px; */
 }

 .c-padding {
   margin-top: 30px;
 }

 .content-body {
   padding:10px;
 }

 


 </style>

app/views/follows/follow.js.erb
$("<%= @id_name %>").html('<%= escape_javascript("follows/follow", community: @community
) %>');

app/views/follows/unfollow.js.erb
 $("<%= @id_name %>").html('<%= escape_javascript("follows/follow", community: @community ) %>'); 

app/views/layouts/application.html.erb
  <head>
    <title>JoinApp3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
     
  </head>

<body>

    <%if flash[:notice]%>
      <div>
        <p class="notice"><%= notice %></p>
      </div>
    <%end%>


    <%if flash[:alert]%>
      <div>
        <p class="alert"><%= alert %></p>
      </div>
    <%end%>
   
  <header class="c-header"> 
    <div class="logo">
      <%= link_to 'JSPORT', root_path, class: "p-absolute"%>
    </div>


    
    
      <div class="dropdown dropleft">
        <button class="btn btn-secondary dropdown-toggle　" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="material-icons">
        account_circle
        </span>  
        </button>




        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% if user_signed_in? %>
            <%= link_to "TOP" ,root_path ,class:"dropdown-item " %>
            <%= link_to "コミュニティを作成", new_community_path(id: current_user),class:"dropdown-item " %>
            <%= link_to  "プロフィール" ,profile_mypage_path(id: current_user),class:"dropdown-item "  %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class:"dropdown-item " %>
        <div>
      </div>
          <%else%>
            <div class="before_contents">
              <%= link_to "ログイン", new_user_session_path %>
              <%= link_to "新規登録", new_user_registration_path %>
            </div>
          <%end%>   
  </header>


  <footer class="footer">
  </footer>

<%= yield %>
  <!-- jQuery読み込み -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <!-- PopperのJS読み込み -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <!-- BootstrapのJS読み込み -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

  
  </body>





<style>

  body {
    background-color: #A9A9A9;
    
  }
 
  .join {
    background-color: #00CCFF;

    }

  .c-header {
    display: flex;
    height: 60px;
    background-color: #08AEEA;
    background-image: linear-gradient(0deg, #08AEEA 0%, #2AF598 100%);
    margin-bottom: 20px;
    box-shadow: 5px 5px 5px rgba(0,0,0,0.4); 
    justify-content: space-between;
    align-items: center;
    
  
  }

  .p-absolute {
    
    font-size:30px;
    padding: 10px;
    color: white;
  }

  .dropdown {
    padding-right:10px;
    
  }

 
/* 
.footer {
  position: absolute;
  width: 100%;

  height: 60px;
  background: #fff;
  color: #000;
  margin-top: auto;

 
} */


</style>

app/views/mypage/profile.html.erb
  <table class="table table-bordered" height="150", width="700">
      <th colspan="4", style="text-align:center;">プロフィール</th> 
    <tr>
      <td>
      <%= image_tag @user.profile_image.url unless @user.profile_image.nil? %>
      </td>
      
      <td class="v-align">
      <%= @user.username %> 
      </td> 
      
      <td width="400">
      <%= safe_join(@user.profile.split("\n"),tag(:br))%>
      </td>

      <td class="v-align">
      <%= link_to "編集", edit_user_path(@user), class: "b-edit" %>
      </td>
    </tr>
  </table>


<style>
img {
  width: 120px;
  height:120px;
  border-radius: 50%;
  
   
}

.table {
  width: 50%;
  margin: auto;
  margin-top: 200px;
  background-color: white;
}

table .v-align {
  vertical-align:middle;
}











</style>

app/views/users/edit.html.erb
<h5>プロフィール編集</h5>
  <div class= "container">
    <div class="col">
      <div class="card mb-4 " style="width: 25rem;">
          <%= form_for @user do |f| %>
              <div class="field">
              <%= f.label  :username, "ユーザー名",class: "label" %>
              <%= f.text_field :username, class: "form-control-md input", :style => "width: 20rem;"  %>
              </div>

              <div class="field">
              <%= f.label :profile, "プロフィール", class: "label" %>
              <%= f.text_area :profile, :wrap => "hard", class: "form-control-md textarea p-field", :style => "width: 20rem;" %>
              </div>

              
              <div class="field">
              <%= f.label :profile_image, "プロフィール画像", class: "label" %>
              <%= f.file_field :profile_image, class: "form-control-md input" %>
              </div>

              <div class="field">
              <%= f.submit "更新", class: " btn btn-primary btn-md f-post" %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>


<style>
  .field {
    padding-bottom: 30px;
      
  }

  .card {
   padding: 40px ;
   height:500px; 
   margin-left: 350px;

  }

 .f-post {
   border-radius: 30px;
   margin-left: 90px;
   width: 150px;
   margin-top: 40px;
 }

 h5 {
   text-align:center;
   padding-top: 50px;
 }

 .p-field {
   height: 80px;
 }

</style>
    





    

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>